# Copyright (c) 2020-2021, NVIDIA CORPORATION.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: Build, test, and publish a PyPi wheel

on:
  workflow_call:
    inputs:
      dry-run:
        required: false
        description: Upload to PyPy Test instance
        type: boolean
        default: true
      python-package:
        type: string
        description: Name of Python package
      python-version:
        type: string
        description: Python version
        default: "3.10"
        required: false
      ref:
        required: false
        description: Ref (SHA or branch) to release
        type: string
        default: ${{ github.sha }}
      packaging:
        required: false
        description: "Packaging tool (supported: setuptools, hatch, uv)"
        type: string
        default: setuptools
      no-publish:
        required: false
        description: Do not publish the wheel
        type: boolean
        default: false
      has-src-dir:
        required: false
        description: Whether the package has a src directory
        type: boolean
        default: false
      skip-test-wheel:
        required: false
        description: Skip the test wheel step
        type: boolean
        default: false
      custom-container:
        required: false
        description: Custom container to use for the build
        type: string
        default: ""
      runner:
        required: false
        description: Runner to use for the build
        type: string
        default: ubuntu-latest
      no-build-isolation:
        required: false
        description: Do not build the package in isolation
        type: boolean
        default: false
      submodules:
        required: false
        description: Whether to checkout submodules
        type: string
        default: ""
      root-dir:
        required: false
        description: Navigate into a sub-directory (mind the / at the end)
        type: string
        default: "./"
      container-options:
        required: false
        description: Options to pass to the container
        type: string
        default: " "
    secrets:
      TWINE_USERNAME:
        required: true
      TWINE_PASSWORD:
        required: true
      SLACK_WEBHOOK_ADMIN:
        required: false
      SLACK_WEBHOOK:
        required: false
      GH_TOKEN:
        required: false
    outputs:
      version:
        description: NeMo library version
        value: ${{ jobs.build-wheel.outputs.expected-version }}
      pypi-name:
        description: NeMo library name on PyPi
        value: ${{ jobs.build-wheel.outputs.name }}

defaults:
  run:
    shell: bash -x -e -u -o pipefail {0}

jobs:
  build-wheel:
    runs-on: ${{ inputs.runner }}
    container:
      image: ${{ inputs.custom-container || '' }}
      options: ${{ inputs.container-options }}
    outputs:
      expected-version: ${{ steps.build.outputs.version }}
      name: ${{ steps.build.outputs.name }}
    env:
      PYPROJECT_NAME: ${{ inputs.python-package }}
      DRY_RUN: ${{ inputs.dry-run }}
      PACKAGING: ${{ inputs.packaging }}
      ROOTDIR: ${{ inputs.root-dir }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ${{ github.run_id }}
          ref: ${{ inputs.ref }}
          submodules: ${{ inputs.submodules }}

      - name: Get Python version
        id: python-version
        run: |
          cd ${{ github.run_id }}
          cd $ROOTDIR

          if [[ "$PACKAGING" == "uv" ]]; then
            if [ -f ".python-version" ]; then
              PYTHON_VERSION=$(cat .python-version)
            else
              echo "Error: .python-version file not found for uv packaging"
              exit 1
            fi
          else
            PYTHON_VERSION="${{ inputs.python-version }}"
          fi
          echo "version=$PYTHON_VERSION" >> $GITHUB_OUTPUT

      - name: Setup Python ${{ steps.python-version.outputs.version }}
        uses: actions/setup-python@v5
        if: inputs.custom-container == ''
        with:
          python-version: "${{ steps.python-version.outputs.version }}"

      - name: Build wheel
        id: build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SRC_DIR: ${{ inputs.has-src-dir && 'src/' || '' }}
          NO_BUILD_ISOLATION: ${{ inputs.no-build-isolation }}
        run: |
          cd ${{ github.run_id }}
          cd $ROOTDIR
          ls -al

          if [[ "$GH_TOKEN" != "" ]]; then
            echo "machine github.com login x-access-token password $GH_TOKEN" > ~/.netrc
            chmod 600 ~/.netrc
          fi

          # Install the package to import and check the version in a later step
          if [[ "$PACKAGING" == "uv" ]]; then
            # Install uv
            curl -LsSf https://astral.sh/uv/0.7.2/install.sh | sh
            export PATH="$HOME/.local/bin:$PATH"
            uv venv --system-site-packages .venv
            source .venv/bin/activate
            if [[ "$NO_BUILD_ISOLATION" == "true" ]]; then
              uv pip install torch
              uv pip install --upgrade setuptools pybind11 wheel_stub packaging poetry
            fi
            uv pip install $([[ "$NO_BUILD_ISOLATION" == "true" ]] && echo "--no-build-isolation" || "") -e .
          else
            if [[ "$NO_BUILD_ISOLATION" == "true" ]]; then
              pip install torch
              pip install --upgrade setuptools pybind11 wheel_stub packaging
            fi
            pip install -e $([[ "$NO_BUILD_ISOLATION" == "true" ]] && echo "--no-build-isolation" || "") .
          fi

          # If this is a dry run, update the patch version to a random number to upload to test-pypi
          if [[ "$DRY_RUN" == "true" ]]; then
            if [[ "$PACKAGING" == "setuptools" || "$PACKAGING" == "uv" ]]; then
              sed -i "/^PATCH/c\PATCH = $((RANDOM % 9000 + 1000))" "$SRC_DIR${PYPROJECT_NAME//.//}/package_info.py"
            else
              RANDOM_DEV=$((RANDOM % 9000 + 1000))
              pip install hatch
              VERSION=$(hatch version | sed -E "s/(dev)[0-9]*/\1$RANDOM_DEV/")
              hatch version $VERSION
            fi
          fi

          # Build the wheel
          if [[ "$PACKAGING" == "uv" ]]; then
            uv build --out-dir ./dist/ .
          else
            python3 -m pip install --upgrade build
            python3 -m build --outdir ./dist/
          fi

          # Get the expected version and name of the package
          cmd=$(cat <<EOF
          import $PYPROJECT_NAME

          with open("version.txt", "w") as fh:
            fh.write($PYPROJECT_NAME.__version__)
          with open("name.txt", "w") as fh:
            fh.write($PYPROJECT_NAME.__package_name__)
          EOF
          )

          if [[ "$PACKAGING" == "uv" ]]; then
            uv run --no-sync --active python -c "$cmd"
          else
            python -c "$cmd"
          fi

          EXPECTED_VERSION=$(cat version.txt)
          NAME=$(cat name.txt | tr '_' '-')

          echo "version=$EXPECTED_VERSION" | tee -a "$GITHUB_OUTPUT"
          echo "name=$NAME" | tee -a "$GITHUB_OUTPUT"

          ls -al dist/

          echo "DIST_DIR=$(pwd)/dist" | tee -a "$GITHUB_OUTPUT"

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: pip-wheel-${{ github.run_id }}-${{ inputs.python-package || 'none' }}
          path: ${{ steps.build.outputs.DIST_DIR }}
          overwrite: true

  test-wheel:
    needs: build-wheel
    runs-on: ubuntu-latest
    if: inputs.skip-test-wheel == false
    env:
      PYPROJECT_NAME: ${{ inputs.python-package }}
      EXPECTED_VERSION: ${{ needs.build-wheel.outputs.expected-version }}
      PACKAGING: ${{ inputs.packaging }}
      ROOTDIR: ${{ inputs.root-dir }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ${{ github.run_id }}
          ref: ${{ inputs.ref }}

      - name: Download wheel
        uses: actions/download-artifact@v4
        with:
          name: pip-wheel-${{ github.run_id }}-${{ inputs.python-package || 'none' }}
          path: dist/${{ github.run_id }}/

      - name: Get Python version
        id: python-version
        run: |
          cd ${{ github.run_id }}
          cd $ROOTDIR

          if [[ "$PACKAGING" == "uv" ]]; then
            if [ -f ".python-version" ]; then
              PYTHON_VERSION=$(cat .python-version)
            else
              echo "Error: .python-version file not found for uv packaging"
              exit 1
            fi
          else
            PYTHON_VERSION="${{ inputs.python-version }}"
          fi
          echo "version=$PYTHON_VERSION" >> $GITHUB_OUTPUT

      - name: Setup Python ${{ steps.python-version.outputs.version }}
        uses: actions/setup-python@v5
        with:
          python-version: "${{ steps.python-version.outputs.version }}"

      - name: Install wheel
        run: |
          if [[ "$PACKAGING" == "uv" ]]; then
            # Install uv
            curl -LsSf https://astral.sh/uv/install.sh | sh

            # Create and activate virtual environment
            uv venv .venv
            source .venv/bin/activate
          fi

          cd dist/${{ github.run_id }}/

          ls -al

          if [[ "$PACKAGING" == "uv" ]]; then
            uv pip install *.whl
          else
            pip install *.whl
          fi

          cmd=$(cat <<EOF
          import $PYPROJECT_NAME

          with open("version.txt", "w") as fh:
            fh.write($PYPROJECT_NAME.__version__)
          EOF
          )

          python -c "$cmd"

          INSTALLED_VERSION=$(cat version.txt)

          if [[ "$INSTALLED_VERSION" != "$EXPECTED_VERSION" ]]; then
            echo 'Wheel has an outdated version, mission abort immediately!'
            exit 1
          fi

  publish-wheel:
    needs: test-wheel
    runs-on: ubuntu-latest
    if: |
      inputs.no-publish == false &&
      (
        inputs.skip-test-wheel == false || !cancelled()
      )
    environment:
      name: ${{ inputs.dry-run && 'public' || 'main' }}
    steps:
      - name: Download wheel
        uses: actions/download-artifact@v4
        with:
          name: pip-wheel-${{ github.run_id }}-${{ inputs.python-package || 'none' }}
          path: dist/

      - name: Validate wheel
        run: |
          python3 -m pip install --upgrade twine==6.0.1
          python3 -m twine check dist/*

      - name: Release wheel
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          REPOSITORY: ${{ inputs.dry-run && 'testpypi' || 'pypi' }}
        run: |
          python3 -m twine upload --verbose --skip-existing -u $TWINE_USERNAME -p $TWINE_PASSWORD --repository $REPOSITORY dist/*

  notify:
    runs-on: ubuntu-latest
    if: failure()
    environment: public
    needs: [publish-wheel]
    env:
      RUN_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
      SLACK_WEBHOOK_ADMIN: "<!subteam^${{ secrets.SLACK_WEBHOOK_ADMIN }}>"
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      COMMIT_URL: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
      COMMIT_SHA: ${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: NVIDIA-NeMo/FW-CI-templates
          ref: v0.17.0
          path: send-slack-alert

      - name: Send Slack alert
        uses: ./send-slack-alert/.github/actions/send-slack-alert
        with:
          message: >
            <${{ env.RUN_URL }}|Build, test, and push PyPi wheel (test)> has failed for <${{ env.COMMIT_URL }}|${{ env.COMMIT_SHA }}>.
            
            cc: ${{ env.SLACK_WEBHOOK_ADMIN }}


          webhook: ${{ env.SLACK_WEBHOOK }}
